all: complete

complete:seclocker trackficall: complete

complete:seclocker interceptor downloader

seclocker: 
        gcc -o bin/seclocker seclocker.c

interceptor:
        gcc -o bin/intercepthor inter.c

downloader: 
        gcc -o bin/downloader downloader.c -lcurl


seclocker: 
        gcc -o bin/seclocker seclocker.c

trackfic:
        gcc -o bin/tackfic trackfic.c
